## importing libraries 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statistics as stats
import seaborn as sns
import zipfile
import os
%matplotlib inline

## importing data and customize display options

In [2]:
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 50)
 
csv_files_normal = [ 
    'normal/12.288.csv', 'normal/13.1072.csv', 'normal/14.336.csv', 'normal/15.1552.csv', 'normal/16.1792.csv',
    'normal/17.2032.csv', 'normal/18.432.csv', 'normal/19.6608.csv', 'normal/20.2752.csv', 'normal/21.7088.csv',
    'normal/22.3232.csv', 'normal/23.552.csv', 'normal/24.576.csv', 'normal/25.6.csv', 'normal/26.624.csv',
    'normal/27.4432.csv', 'normal/28.8768.csv', 'normal/29.4912.csv', 'normal/30.72.csv', 'normal/31.744.csv',
    'normal/32.9728.csv', 'normal/33.5872.csv', 'normal/34.2016.csv', 'normal/35.4304.csv', 'normal/36.4544.csv',
    'normal/37.6832.csv', 'normal/38.2976.csv', 'normal/39.3216.csv','normal/40.3456.csv', 'normal/41.7792.csv',
    'normal/42.3936.csv', 'normal/43.6224.csv', 'normal/44.6464.csv', 'normal/45.4656.csv', 'normal/46.2848.csv',
    'normal/47.7184.csv', 'normal/48.9472.csv', 'normal/49.5616.csv', 'normal/51.8144.csv', 'normal/52.4288.csv',
    'normal/53.8624.csv', 'normal/54.6816.csv', 'normal/55.7056.csv', 'normal/56.7296.csv', 'normal/57.9584.csv',
    'normal/58.7776.csv', 'normal/59.5968.csv', 'normal/60.416.csv', 'normal/61.44.csv' 
] 
normal = []

for file in csv_files_normal:
    df = pd.read_csv(file)
    normal.append(df)

normal_arr = np.array(normal)
normal_n = normal_arr.reshape(-1,normal_arr.shape[-1])
normal_df = pd.DataFrame(normal_n,columns=['A','B','C','D','E','F','G','H'])
normal_df.head()

A         B         C         D        E         F        G         H
0  4.6038 -0.051295 -0.194050 -0.060071 -0.41809  0.036547 -0.11043  0.118310
1  4.5703 -0.969080  0.038033 -0.028329 -0.43081  0.041924 -0.14331 -0.071527
2  4.5870  0.891270  0.072973  0.007453 -0.40017  0.041090 -0.11984  0.043445
3  4.5887 -1.716000 -0.329290 -0.033063 -0.50281  0.040474 -0.25270  0.023901
4  4.5675  1.240300  0.354010  0.040460 -0.36806  0.044062 -0.14258 -0.054880

In [3]:
csv_files_SixG = [ 
    'imbalance/6g/13.9264.csv', 'imbalance/6g/14.336.csv', 'imbalance/6g/15.36.csv', 'imbalance/6g/16.1792.csv', 'imbalance/6g/17.408.csv',
    'imbalance/6g/18.432.csv', 'imbalance/6g/19.6608.csv', 'imbalance/6g/20.2752.csv', 'imbalance/6g/21.7088.csv', 'imbalance/6g/22.7328.csv',
    'imbalance/6g/23.552.csv', 'imbalance/6g/24.576.csv', 'imbalance/6g/25.3952.csv', 'imbalance/6g/26.8288.csv', 'imbalance/6g/27.648.csv',
    'imbalance/6g/28.8768.csv', 'imbalance/6g/29.4912.csv', 'imbalance/6g/30.5152.csv', 'imbalance/6g/31.5392.csv', 'imbalance/6g/32.9728.csv',
    'imbalance/6g/33.9968.csv', 'imbalance/6g/34.816.csv', 'imbalance/6g/35.6352.csv', 'imbalance/6g/36.4544.csv', 'imbalance/6g/37.6832.csv',
    'imbalance/6g/38.5024.csv', 'imbalance/6g/39.3216.csv', 'imbalance/6g/40.7552.csv','imbalance/6g/41.3696.csv', 'imbalance/6g/42.5984.csv',
    'imbalance/6g/43.4176.csv', 'imbalance/6g/44.4416.csv', 'imbalance/6g/45.4656.csv', 'imbalance/6g/46.6944.csv', 'imbalance/6g/47.3088.csv',
    'imbalance/6g/48.128.csv', 'imbalance/6g/49.152.csv', 'imbalance/6g/50.5856.csv', 'imbalance/6g/51.8144.csv', 'imbalance/6g/52.224.csv',
    'imbalance/6g/53.6576.csv', 'imbalance/6g/54.4768.csv', 'imbalance/6g/55.296.csv', 'imbalance/6g/56.1152.csv', 'imbalance/6g/58.1632.csv',
    'imbalance/6g/58.7776.csv', 'imbalance/6g/59.392.csv', 'imbalance/6g/60.2112.csv', 'imbalance/6g/62.0544.csv' 
]
SixG = []

for file in csv_files_SixG:
    df2=pd.read_csv(file)
    SixG.append(df2)

SixG_arr = np.array(SixG)
SixG_n = SixG_arr.reshape(-1,SixG_arr.shape[-1])
SixG_df = pd.DataFrame(SixG_n,columns=['A','B','C','D','E','F','G','H'])
SixG_df.head()

A        B        C         D        E         F        G         H
0 -0.52322 -0.28902 -0.31740 -0.001450 -0.19779 -0.023694 -0.28712 -0.018203
1 -0.55320  1.64770  0.41715  0.038655 -0.18563 -0.021564 -0.21215 -0.072039
2 -0.57723  0.15914 -0.33321 -0.011148 -0.19892 -0.025401 -0.30076 -0.007373
3 -0.49280  1.31650  0.41147  0.028096 -0.19165 -0.022879 -0.24147 -0.108590
4 -0.61773  0.69420 -0.23371 -0.002092 -0.19707 -0.024991 -0.27857  0.018571

In [4]:
csv_files_TenG = [ 
    'imbalance/10g/13.9264.csv', 'imbalance/10g/14.5408.csv', 'imbalance/10g/15.7696.csv', 'imbalance/10g/16.5888.csv', 'imbalance/10g/17.2032.csv',
    'imbalance/10g/18.2272.csv', 'imbalance/10g/19.2512.csv', 'imbalance/10g/20.48.csv', 'imbalance/10g/21.7088.csv', 'imbalance/10g/22.1184.csv',
    'imbalance/10g/22.9376.csv', 'imbalance/10g/24.7808.csv', 'imbalance/10g/25.6.csv', 'imbalance/10g/26.0096.csv', 'imbalance/10g/27.648.csv',
    'imbalance/10g/28.672.csv', 'imbalance/10g/29.4912.csv', 'imbalance/10g/30.3104.csv', 'imbalance/10g/31.744.csv', 'imbalance/10g/32.768.csv',
    'imbalance/10g/33.5872.csv', 'imbalance/10g/34.4064.csv', 'imbalance/10g/36.0448.csv', 'imbalance/10g/36.864.csv', 'imbalance/10g/38.5024.csv',
    'imbalance/10g/39.1168.csv', 'imbalance/10g/40.5504.csv', 'imbalance/10g/41.7792.csv','imbalance/10g/42.1888.csv', 'imbalance/10g/43.2128.csv',
    'imbalance/10g/44.6464.csv', 'imbalance/10g/45.4656.csv', 'imbalance/10g/46.08.csv', 'imbalance/10g/47.5136.csv', 'imbalance/10g/48.5376.csv',
    'imbalance/10g/49.9712.csv', 'imbalance/10g/50.5856.csv', 'imbalance/10g/51.4048.csv', 'imbalance/10g/52.6336.csv', 'imbalance/10g/53.8624.csv',
    'imbalance/10g/55.0912.csv', 'imbalance/10g/55.9104.csv', 'imbalance/10g/56.9344.csv', 'imbalance/10g/57.9584.csv', 'imbalance/10g/59.1872.csv',
    'imbalance/10g/60.0064.csv', 'imbalance/10g/61.0304.csv', 'imbalance/10g/61.8496.csv'
]

TenG = []

for file in csv_files_TenG:
    df3=pd.read_csv(file)
    TenG.append(df3)

TenG_arr = np.array(TenG)
TenG_n = TenG_arr.reshape(-1,TenG_arr.shape[-1])
TenG_df = pd.DataFrame(TenG_n,columns=['A','B','C','D','E','F','G','H'])
TenG_df.head()

A        B         C         D        E         F        G         H
0  4.6252 -0.65002 -0.399110 -0.023339  0.15131  0.032407  0.10908 -0.029934
1  4.5657  0.50367  0.417000  0.029059  0.15085  0.030508  0.19411 -0.085132
2  4.6220  0.22507 -0.272730 -0.019793  0.14843  0.027678  0.15055  0.058802
3  4.5747 -0.26502  0.200050  0.004126  0.14428  0.026291  0.15064 -0.070481
4  4.6044  1.29190  0.048915  0.022341  0.14987  0.028031  0.19017 -0.009588

## Oversampling all dataset to the size of the larger one

In [5]:
print(normal_df.shape)
print('\n\n',SixG_df.shape)
print('\n\n',TenG_df.shape)

(12249951, 8)


 (12249951, 8)


 (11999952, 8)


In [6]:
import pandas as pd 
from sklearn.utils import resample 
 
max_size = max(len(normal_df), len(SixG_df), len(TenG_df)) 
  
normal_oversampled = resample(normal_df, replace=True, n_samples=max_size, random_state=42) 
TenG_oversampled = resample(TenG_df, replace=True, n_samples=max_size, random_state=42) 
 
normal_oversampled = normal_oversampled.iloc[:, :8]  
TenG_oversampled = TenG_oversampled.iloc[:, :8] 
SixG_df = SixG_df.iloc[:, :8]  
 
normal_oversampled.columns = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'] 
TenG_oversampled.columns = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'] 
SixG_df.columns = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'] 

In [7]:
print(normal_oversampled.shape)
print('\n\n',SixG_df.shape)
print('\n\n',TenG_oversampled.shape)

(12249951, 8)


 (12249951, 8)


 (12249951, 8)


In [8]:
normal_oversampled['Label'] = 0
normal_oversampled.head()

A         B         C         D         E         F        G  \
6423388   4.41090  0.446870  0.323990  0.117640 -0.904480 -0.022867  0.21077   
6550634  -0.91089  0.439720 -0.021068 -0.169660  0.069058  0.006109 -0.37055   
10081351 -0.70740  0.591590  0.526090 -0.489200 -0.048195 -0.047612  0.25383   
4304572  -0.45556  0.073067 -0.368450  0.169620  0.812170  0.002765  0.50331   
2234489  -0.69771  0.981770 -0.057550  0.094688 -0.549030  0.020984  0.06183   

                 H  Label  
6423388  -0.039937      0  
6550634   0.127820      0  
10081351 -0.160480      0  
4304572  -0.066855      0  
2234489   0.089541      0

In [9]:
SixG_df['Label'] = 1 
SixG_df.head()

A        B        C         D        E         F        G         H  \
0 -0.52322 -0.28902 -0.31740 -0.001450 -0.19779 -0.023694 -0.28712 -0.018203   
1 -0.55320  1.64770  0.41715  0.038655 -0.18563 -0.021564 -0.21215 -0.072039   
2 -0.57723  0.15914 -0.33321 -0.011148 -0.19892 -0.025401 -0.30076 -0.007373   
3 -0.49280  1.31650  0.41147  0.028096 -0.19165 -0.022879 -0.24147 -0.108590   
4 -0.61773  0.69420 -0.23371 -0.002092 -0.19707 -0.024991 -0.27857  0.018571   

   Label  
0      1  
1      1  
2      1  
3      1  
4      1

In [10]:
TenG_oversampled['Label'] = 2
TenG_oversampled.head()

A        B         C         D         E         F        G  \
6423388   4.40400 -0.26397  0.034911 -0.061105  0.021475 -0.000514  0.70043   
6550634  -0.41126  2.11250 -0.266060 -0.034482  0.005676  0.017859  0.48803   
10081351 -0.78319 -0.82413 -0.804380 -0.331430  0.095615  0.011384  0.28429   
4304572  -0.67775 -0.36139 -0.466550  0.170000  0.008097  0.021568  1.27690   
2234489  -0.61440  1.12780  0.313480 -0.014160  0.018315  0.010543 -0.26482   

                 H  Label  
6423388   0.314060      2  
6550634   0.056246      2  
10081351 -0.197040      2  
4304572   0.244890      2  
2234489  -0.070043      2

In [11]:
data = pd.concat([normal_oversampled, SixG_df, TenG_oversampled], ignore_index=True) 
  
print(f"Combined DataFrame size: {data.shape}") 
data.head()

Combined DataFrame size: (36749853, 9)


A         B         C         D         E         F        G  \
0  4.41090  0.446870  0.323990  0.117640 -0.904480 -0.022867  0.21077   
1 -0.91089  0.439720 -0.021068 -0.169660  0.069058  0.006109 -0.37055   
2 -0.70740  0.591590  0.526090 -0.489200 -0.048195 -0.047612  0.25383   
3 -0.45556  0.073067 -0.368450  0.169620  0.812170  0.002765  0.50331   
4 -0.69771  0.981770 -0.057550  0.094688 -0.549030  0.020984  0.06183   

          H  Label  
0 -0.039937      0  
1  0.127820      0  
2 -0.160480      0  
3 -0.066855      0  
4  0.089541      0

In [12]:
print('\n',data.shape)


 (36749853, 9)


## Handling Duplicates 

In [13]:
duplicates = data[data.duplicated()]
print('Duplicates of All Columns:\n', duplicates.count())

Duplicates of All Columns:
 A        9080466
B        9080466
C        9080466
D        9080466
E        9080466
F        9080466
G        9080466
H        9080466
Label    9080466
dtype: int64


In [14]:
cleaned_data = data.drop_duplicates()
print('\n Dataset size after Removing Duplicates:\n', cleaned_data.shape)


 Dataset size after Removing Duplicates:
 (27669387, 9)


## Handling Errors and Outliers

In [15]:
means = cleaned_data.mean()
print(means)

A        0.000213
B        0.004344
C       -0.000091
D        0.000636
E        0.009768
F        0.003079
G        0.049235
H        0.013214
Label    0.997567
dtype: float64


In [16]:
stds = cleaned_data.std()
print(stds)

A        1.722403
B        0.848477
C        0.550304
D        0.227172
E        0.342192
F        0.031460
G        0.698779
H        0.178696
Label    0.746504
dtype: float64


In [17]:
threshold = 3
outliers = cleaned_data[(np.abs((cleaned_data - means) / stds) > threshold).any(axis=1)]
print('\nIdentified Outliers:')
print('\n',outliers)
data_no_outliers = cleaned_data[(np.abs((cleaned_data - means) / stds) <= threshold).all(axis=1)]
print('\nDataset after Removing Outliers\n',data_no_outliers)


Identified Outliers:

                 A        B         C         D         E         F        G  \
9        -0.62477  1.21730  0.489020  0.095170 -1.306500  0.010511 -0.65930   
20       -0.60117  0.69126  0.091969 -0.000165 -1.685900 -0.053241 -0.48623   
27       -0.65493  1.07510 -0.076752  0.046414  1.234800 -0.000617  0.31579   
45       -0.64941 -0.61217 -0.183740 -0.477550  1.397500  0.025990  0.44785   
46       -0.53048 -1.19430 -0.015666 -0.048337 -1.099000 -0.034277 -0.43362   
...           ...      ...       ...       ...       ...       ...      ...   
36749771 -0.38445  0.69882 -0.007777 -0.017545 -0.297480 -0.035528 -2.98430   
36749773 -0.76487  0.13227  2.994600 -0.060013 -0.091990 -0.028142  1.87200   
36749802 -0.55382  0.63564  0.043872  0.866410 -0.232440  0.003188  0.21019   
36749818 -0.67792 -0.19070  0.560080  0.100440 -0.008402 -0.000187 -3.07480   
36749852 -0.66586  1.48710 -0.138330 -0.060624  0.012528 -0.008466 -2.42530   

                 H  Label  

In [18]:
df = data_no_outliers 
print('\n',df.shape)


 (25465907, 9)


In [19]:
df.head(10)

A         B         C         D         E         F         G  \
0   4.41090  0.446870  0.323990  0.117640 -0.904480 -0.022867  0.210770   
1  -0.91089  0.439720 -0.021068 -0.169660  0.069058  0.006109 -0.370550   
2  -0.70740  0.591590  0.526090 -0.489200 -0.048195 -0.047612  0.253830   
3  -0.45556  0.073067 -0.368450  0.169620  0.812170  0.002765  0.503310   
4  -0.69771  0.981770 -0.057550  0.094688 -0.549030  0.020984  0.061830   
5  -0.82586  1.115100  0.905780 -0.267260 -0.069877  0.020663 -0.537280   
6  -0.64627 -0.396880  0.271370 -0.234260  0.019246  0.021645  0.479560   
7  -0.70178  0.756310 -0.311430  0.045367 -0.022692  0.030867 -0.075591   
8  -0.69679 -0.050171 -0.372350  0.356500 -0.065382 -0.003755 -0.281780   
10 -0.72819 -0.169790  0.181770  0.209610  0.015977  0.024495  0.215700   

           H  Label  
0  -0.039937      0  
1   0.127820      0  
2  -0.160480      0  
3  -0.066855      0  
4   0.089541      0  
5  -0.082650      0  
6  -0.265650      0  
7  -0.019079      0  
8  -0.156440      0  
10 -0.192410      0

In [20]:
df['rolling_mean_A'] = df['A'].rolling(window=20, min_periods=5).mean()
df['rolling_std_A'] = df['A'].rolling(window=20, min_periods=5).std()
df['rolling_mean_B'] = df['B'].rolling(window=20, min_periods=5).mean()
df['rolling_std_B'] = df['B'].rolling(window=20, min_periods=5).std()
df['rolling_mean_C'] = df['C'].rolling(window=20, min_periods=5).mean()
df['rolling_std_C'] = df['C'].rolling(window=20, min_periods=5).std()
df['rolling_mean_D'] = df['D'].rolling(window=20, min_periods=5).mean()
df['rolling_std_D'] = df['D'].rolling(window=20, min_periods=5).std()
df['rolling_mean_E'] = df['E'].rolling(window=20, min_periods=5).mean()
df['rolling_std_E'] = df['E'].rolling(window=20, min_periods=5).std()
df['rolling_mean_F'] = df['F'].rolling(window=20, min_periods=5).mean()
df['rolling_std_F'] = df['F'].rolling(window=20, min_periods=5).std()
df['rolling_mean_G'] = df['G'].rolling(window=20, min_periods=5).mean()
df['rolling_std_G'] = df['G'].rolling(window=20, min_periods=5).std()
df['rolling_mean_H'] = df['H'].rolling(window=20, min_periods=5).mean()
df['rolling_std_H'] = df['H'].rolling(window=20, min_periods=5).std()

C:\Users\Bashir Rayaneh\AppData\Local\Temp\ipykernel_19092\4266758952.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rolling_mean_A'] = df['A'].rolling(window=20, min_periods=5).mean()
C:\Users\Bashir Rayaneh\AppData\Local\Temp\ipykernel_19092\4266758952.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rolling_std_A'] = df['A'].rolling(window=20, min_periods=5).std()
C:\Users\Bashir Rayaneh\AppData\Local\Temp\ipykernel_19092\4266758952.py:3: SettingWithCopyWarning: 
A value is trying to be s

In [21]:
df.head(10)

A         B         C         D         E         F         G  \
0   4.41090  0.446870  0.323990  0.117640 -0.904480 -0.022867  0.210770   
1  -0.91089  0.439720 -0.021068 -0.169660  0.069058  0.006109 -0.370550   
2  -0.70740  0.591590  0.526090 -0.489200 -0.048195 -0.047612  0.253830   
3  -0.45556  0.073067 -0.368450  0.169620  0.812170  0.002765  0.503310   
4  -0.69771  0.981770 -0.057550  0.094688 -0.549030  0.020984  0.061830   
5  -0.82586  1.115100  0.905780 -0.267260 -0.069877  0.020663 -0.537280   
6  -0.64627 -0.396880  0.271370 -0.234260  0.019246  0.021645  0.479560   
7  -0.70178  0.756310 -0.311430  0.045367 -0.022692  0.030867 -0.075591   
8  -0.69679 -0.050171 -0.372350  0.356500 -0.065382 -0.003755 -0.281780   
10 -0.72819 -0.169790  0.181770  0.209610  0.015977  0.024495  0.215700   

           H  Label  rolling_mean_A  rolling_std_A  rolling_mean_B  \
0  -0.039937      0             NaN            NaN             NaN   
1   0.127820      0             NaN            NaN             NaN   
2  -0.160480      0             NaN            NaN             NaN   
3  -0.066855      0             NaN            NaN             NaN   
4   0.089541      0        0.327868       2.288177        0.506603   
5  -0.082650      0        0.135580       2.100108        0.608020   
6  -0.265650      0        0.023887       1.939769        0.464462   
7  -0.019079      0       -0.066821       1.814111        0.500943   
8  -0.156440      0       -0.136818       1.709889        0.439708   
10 -0.192410      0       -0.195955       1.622909        0.378759   

    rolling_std_B  rolling_mean_C  rolling_std_C  rolling_mean_D  \
0             NaN             NaN            NaN             NaN   
1             NaN             NaN            NaN             NaN   
2             NaN             NaN            NaN             NaN   
3             NaN             NaN            NaN             NaN   
4        0.327491        0.080602       0.349560       -0.055382   
5        0.384072        0.218132       0.459608       -0.090695   
6        0.516901        0.225737       0.420045       -0.111205   
7        0.489555        0.158591       0.432783       -0.091633   
8        0.493410        0.099598       0.441827       -0.041841   
10       0.503539        0.107815       0.417368       -0.016696   

    rolling_std_D  rolling_mean_E  rolling_std_E  rolling_mean_F  \
0             NaN             NaN            NaN             NaN   
1             NaN             NaN            NaN             NaN   
2             NaN             NaN            NaN             NaN   
3             NaN             NaN            NaN             NaN   
4        0.275836       -0.124095       0.653688       -0.008124   
5        0.261439       -0.115059       0.585095       -0.003326   
6        0.244751       -0.095873       0.536523        0.000241   
7        0.233259       -0.086725       0.497397        0.004069   
8        0.264428       -0.084354       0.465327        0.003200   
10       0.261679       -0.074320       0.439860        0.005329   

    rolling_std_F  rolling_mean_G  rolling_std_G  rolling_mean_H  \
0             NaN             NaN            NaN             NaN   
1             NaN             NaN            NaN             NaN   
2             NaN             NaN            NaN             NaN   
3             NaN             NaN            NaN             NaN   
4        0.027134        0.131838       0.322645       -0.009982   
5        0.026965        0.020318       0.397366       -0.022094   
6        0.026363        0.085924       0.402134       -0.056887   
7        0.026702        0.065735       0.376658       -0.052161   
8        0.025113        0.027122       0.370885       -0.063748   
10       0.024616        0.045980       0.354722       -0.076614   

    rolling_std_H  
0             NaN  
1             NaN  
2             NaN  
3             NaN  
4        0.117979  
5        0.109614  
6        0.135967  
7     

In [22]:
df_final = df.drop(['A', 'B', 'C', 'E', 'D', 'E', 'F', 'G', 'H'], axis=1)
df_final.head()

Label  rolling_mean_A  rolling_std_A  rolling_mean_B  rolling_std_B  \
0      0             NaN            NaN             NaN            NaN   
1      0             NaN            NaN             NaN            NaN   
2      0             NaN            NaN             NaN            NaN   
3      0             NaN            NaN             NaN            NaN   
4      0        0.327868       2.288177        0.506603       0.327491   

   rolling_mean_C  rolling_std_C  rolling_mean_D  rolling_std_D  \
0             NaN            NaN             NaN            NaN   
1             NaN            NaN             NaN            NaN   
2             NaN            NaN             NaN            NaN   
3             NaN            NaN             NaN            NaN   
4        0.080602        0.34956       -0.055382       0.275836   

   rolling_mean_E  rolling_std_E  rolling_mean_F  rolling_std_F  \
0             NaN            NaN             NaN            NaN   
1             NaN            NaN             NaN            NaN   
2             NaN            NaN             NaN            NaN   
3             NaN            NaN             NaN            NaN   
4       -0.124095       0.653688       -0.008124       0.027134   

   rolling_mean_G  rolling_std_G  rolling_mean_H  rolling_std_H  
0             NaN            NaN             NaN            NaN  
1             NaN            NaN             NaN            NaN  
2             NaN            NaN             NaN            NaN  
3             NaN            NaN             NaN            NaN  
4        0.131838       0.322645       -0.009982       0.117979

In [23]:
df_final = df_final.dropna()
df_final.head()

Label  rolling_mean_A  rolling_std_A  rolling_mean_B  rolling_std_B  \
4      0        0.327868       2.288177        0.506603       0.327491   
5      0        0.135580       2.100108        0.608020       0.384072   
6      0        0.023887       1.939769        0.464462       0.516901   
7      0       -0.066821       1.814111        0.500943       0.489555   
8      0       -0.136818       1.709889        0.439708       0.493410   

   rolling_mean_C  rolling_std_C  rolling_mean_D  rolling_std_D  \
4        0.080602       0.349560       -0.055382       0.275836   
5        0.218132       0.459608       -0.090695       0.261439   
6        0.225737       0.420045       -0.111205       0.244751   
7        0.158591       0.432783       -0.091633       0.233259   
8        0.099598       0.441827       -0.041841       0.264428   

   rolling_mean_E  rolling_std_E  rolling_mean_F  rolling_std_F  \
4       -0.124095       0.653688       -0.008124       0.027134   
5       -0.115059       0.585095       -0.003326       0.026965   
6       -0.095873       0.536523        0.000241       0.026363   
7       -0.086725       0.497397        0.004069       0.026702   
8       -0.084354       0.465327        0.003200       0.025113   

   rolling_mean_G  rolling_std_G  rolling_mean_H  rolling_std_H  
4        0.131838       0.322645       -0.009982       0.117979  
5        0.020318       0.397366       -0.022094       0.109614  
6        0.085924       0.402134       -0.056887       0.135967  
7        0.065735       0.376658       -0.052161       0.126588  
8        0.027122       0.370885       -0.063748       0.123409

In [24]:
df_final.shape

(25465903, 17)

In [ ]:
from sklearn.feature_selection import SelectKBest, f_classif
X = df_final.drop('Label', axis=1)
y = df_final['Label']
selector = SelectKBest(score_func=f_classif, k=6)
selected_features = selector.fit_transform(X, y)
selected_indices = selector.get_support(indices=True)
selected_feature_names = [X.columns[i] for i in selected_indices]
print('Selected Features:')
for feature_name in selected_feature_names:
    print(feature_name)

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
X = df_final.drop('Label', axis=1)
y = df_final['Label']
estimator = LogisticRegression()
rfe = RFE(estimator, n_features_to_select=6)
selected_feautres = rfe.fit_transform(X, y)
selected_indices = rfe.get_support(indices=True)
selected_feature_names = [X.columns[i] for i in selected_indices]
print('Selected Features:')
for feature_name in selected_feature_names:
    print(feature_name)

In [ ]:
from sklearn.linear_model import Lasso
X = df_final.drop('Label', axis=1)
y = df_final['Label']
lasso = Lasso(alpha=0.05)
lasso.fit(X, y)
feature_importances = lasso.coef_
selected_incides = np.nonzero(feature_importances)[0]
selected_feature_names = X.columns[selected_incides]
print('Selected Features:')
for feature_name in selected_feature_names:
    print(feature_name)

In [ ]:
from sklearn.feature_selection import RFECV
from sklearn.linear_model import LogisticRegression
X = df_final.drop('Label', axis=1)
y = df_final['Label']
estimator = LogisticRegression()
rfa = RFECV(estimator, cv=3)
selected_features = rfa.fit_transform(X, y)
selected_indices = rfa.get_support(indices=True)
selected_feature_names = [X.columns[i] for i in selected_indices]
print('Selected Features:')
for feature_name in selected_feature_names:
    print(feature_name)

In [25]:
df_final_2 = df_final.drop(['rolling_mean_B', 'rolling_mean_C', 'rolling_mean_D', 'rolling_mean_E', 'rolling_mean_F'
                          , 'rolling_mean_G', 'rolling_mean_H', 'rolling_std_H'], axis=1)
df_final_2.head()

Label  rolling_mean_A  rolling_std_A  rolling_std_B  rolling_std_C  \
4      0        0.327868       2.288177       0.327491       0.349560   
5      0        0.135580       2.100108       0.384072       0.459608   
6      0        0.023887       1.939769       0.516901       0.420045   
7      0       -0.066821       1.814111       0.489555       0.432783   
8      0       -0.136818       1.709889       0.493410       0.441827   

   rolling_std_D  rolling_std_E  rolling_std_F  rolling_std_G  
4       0.275836       0.653688       0.027134       0.322645  
5       0.261439       0.585095       0.026965       0.397366  
6       0.244751       0.536523       0.026363       0.402134  
7       0.233259       0.497397       0.026702       0.376658  
8       0.264428       0.465327       0.025113       0.370885

In [26]:
shuffled_data = df_final_2.sample(frac=1)
shuffled_data.head(10)

Label  rolling_mean_A  rolling_std_A  rolling_std_B  rolling_std_C  \
17194209      1       -0.686905       0.009169       0.871352       0.303066   
17184337      1       -0.608985       0.027354       0.821457       0.297176   
30995730      2        0.079305       1.871827       0.838160       0.519767   
7553186       0        0.142658       1.865356       0.915428       0.341384   
29379514      2        0.352941       2.108761       0.818469       0.453247   
21141088      1        4.391720       0.008282       0.496233       0.308182   
12786309      1       -0.606069       0.001979       1.216097       0.409284   
3492452       0       -0.409545       1.161417       0.906820       0.432994   
24951894      2        0.093498       1.875581       0.793716       0.573674   
17646066      1       -0.527198       0.041803       0.709522       0.370100   

          rolling_std_D  rolling_std_E  rolling_std_F  rolling_std_G  
17194209       0.068316       0.007316       0.002889       0.053123  
17184337       0.078450       0.007059       0.003708       0.054349  
30995730       0.139120       0.098155       0.032935       0.763222  
7553186        0.139736       0.397438       0.032783       0.314939  
29379514       0.229739       0.102978       0.028062       0.765958  
21141088       0.182609       0.005908       0.002598       0.107278  
12786309       0.038982       0.014436       0.005367       0.076369  
3492452        0.121895       0.501596       0.029923       0.285852  
24951894       0.211087       0.095709       0.029195       0.704253  
17646066       0.104835       0.012087       0.009342       0.112970

In [27]:
shuffled_data = shuffled_data.reset_index(drop=True)
shuffled_data.head(10)

Label  rolling_mean_A  rolling_std_A  rolling_std_B  rolling_std_C  \
0      1       -0.686905       0.009169       0.871352       0.303066   
1      1       -0.608985       0.027354       0.821457       0.297176   
2      2        0.079305       1.871827       0.838160       0.519767   
3      0        0.142658       1.865356       0.915428       0.341384   
4      2        0.352941       2.108761       0.818469       0.453247   
5      1        4.391720       0.008282       0.496233       0.308182   
6      1       -0.606069       0.001979       1.216097       0.409284   
7      0       -0.409545       1.161417       0.906820       0.432994   
8      2        0.093498       1.875581       0.793716       0.573674   
9      1       -0.527198       0.041803       0.709522       0.370100   

   rolling_std_D  rolling_std_E  rolling_std_F  rolling_std_G  
0       0.068316       0.007316       0.002889       0.053123  
1       0.078450       0.007059       0.003708       0.054349  
2       0.139120       0.098155       0.032935       0.763222  
3       0.139736       0.397438       0.032783       0.314939  
4       0.229739       0.102978       0.028062       0.765958  
5       0.182609       0.005908       0.002598       0.107278  
6       0.038982       0.014436       0.005367       0.076369  
7       0.121895       0.501596       0.029923       0.285852  
8       0.211087       0.095709       0.029195       0.704253  
9       0.104835       0.012087       0.009342       0.112970

In [28]:
shuffled_data.describe()

Label  rolling_mean_A  rolling_std_A  rolling_std_B  \
count  2.546590e+07    2.546590e+07   2.546590e+07   2.546590e+07   
mean   1.010955e+00    9.381409e-03   9.317054e-01   7.470446e-01   
std    7.343219e-01    1.184662e+00   8.978525e-01   2.404370e-01   
min    0.000000e+00   -9.915530e-01   1.311249e-03   5.964906e-02   
25%    0.000000e+00   -6.536140e-01   3.582358e-02   6.051214e-01   
50%    1.000000e+00   -3.848525e-01   1.132086e+00   7.835837e-01   
75%    2.000000e+00    1.110640e-01   1.856097e+00   9.075890e-01   
max    2.000000e+00    4.607740e+00   2.759017e+00   1.637521e+00   

       rolling_std_C  rolling_std_D  rolling_std_E  rolling_std_F  \
count   2.546590e+07   2.546590e+07   2.546590e+07   2.546590e+07   
mean    4.244906e-01   1.628870e-01   1.486093e-01   2.053178e-02   
std     1.254832e-01   7.415219e-02   1.818869e-01   1.193817e-02   
min     8.292631e-02   8.522253e-03   9.036329e-04   8.413527e-04   
25%     3.297611e-01   1.045039e-01   1.105032e-02   8.297983e-03   
50%     3.946073e-01   1.685749e-01   7.600592e-02   2.406305e-02   
75%     5.041150e-01   2.147619e-01   3.327218e-01   3.095291e-02   
max     1.146159e+00   5.224021e-01   7.668808e-01   5.693101e-02   

       rolling_std_G  
count   2.546590e+07  
mean    3.830497e-01  
std     2.713334e-01  
min     1.067882e-02  
25%     1.418320e-01  
50%     3.297578e-01  
75%     6.091600e-01  
max     1.352261e+00

In [29]:
print(shuffled_data.shape)
print(shuffled_data.isna().sum())

(25465903, 9)
Label             0
rolling_mean_A    0
rolling_std_A     0
rolling_std_B     0
rolling_std_C     0
rolling_std_D     0
rolling_std_E     0
rolling_std_F     0
rolling_std_G     0
dtype: int64


In [30]:
shuffled_data = shuffled_data.reindex(columns=['rolling_mean_A', 'rolling_std_A', 'rolling_std_B',
                                               'rolling_std_C', 'rolling_std_D', 'rolling_std_E', 
                                               'rolling_std_F', 'rolling_std_G', 'Label'])
shuffled_data.head()

rolling_mean_A  rolling_std_A  rolling_std_B  rolling_std_C  rolling_std_D  \
0       -0.686905       0.009169       0.871352       0.303066       0.068316   
1       -0.608985       0.027354       0.821457       0.297176       0.078450   
2        0.079305       1.871827       0.838160       0.519767       0.139120   
3        0.142658       1.865356       0.915428       0.341384       0.139736   
4        0.352941       2.108761       0.818469       0.453247       0.229739   

   rolling_std_E  rolling_std_F  rolling_std_G  Label  
0       0.007316       0.002889       0.053123      1  
1       0.007059       0.003708       0.054349      1  
2       0.098155       0.032935       0.763222      2  
3       0.397438       0.032783       0.314939      0  
4       0.102978       0.028062       0.765958      2

## implenting ANN 

In [31]:
import tensorflow as tf

In [32]:
X = shuffled_data.iloc[:, :-1].values
y = shuffled_data.iloc[:, -1].values

In [33]:
print(y)

[1 1 2 ... 1 2 0]


In [34]:
from sklearn.preprocessing import OneHotEncoder
y = np.array(y).reshape(-1, 1)
encoder = OneHotEncoder(sparse_output=False)
y = encoder.fit_transform(y)

In [35]:
print(y)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [37]:
print(X_train.shape)

(20372722, 8)


In [38]:
print(y_train.shape)

(20372722, 3)


In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=4, activation='relu'))
ann.add(tf.keras.layers.Dense(units=4, activation='relu'))
ann.add(tf.keras.layers.Dense(units=3, activation='softmax'))
ann.compile(optimizer = 'adam' , loss = 'categorical_crossentropy' , metrics = ['accuracy'])
from keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(
    monitor='accuracy',  # or 'val_accuracy' depending on your focus
    patience=2,         # number of epochs with no improvement to wait before stopping
    restore_best_weights=True  # restore weights from the best epoch
)

In [40]:
ann = tf.keras.models.Sequential()

In [41]:
ann.add(tf.keras.layers.Dense(units=4, activation='relu'))

In [42]:
ann.add(tf.keras.layers.Dense(units=4, activation='relu'))

In [43]:
ann.add(tf.keras.layers.Dense(units=3, activation='softmax'))

In [44]:
ann.compile(optimizer = 'adam' , loss = 'categorical_crossentropy' , metrics = ['accuracy'])

In [45]:
from keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(
    monitor='accuracy',  # or 'val_accuracy' depending on your focus
    patience=2,         # number of epochs with no improvement to wait before stopping
    restore_best_weights=True  # restore weights from the best epoch
)

In [46]:
ann.fit(X_train, y_train, batch_size = 128, epochs = 20, callbacks=[early_stopping])

Epoch 1/20
159162/159162 ━━━━━━━━━━━━━━━━━━━━ 102s 629us/step - accuracy: 0.9953 - loss: 0.0184
Epoch 2/20
159162/159162 ━━━━━━━━━━━━━━━━━━━━ 102s 637us/step - accuracy: 1.0000 - loss: 1.1002e-04
Epoch 3/20
159162/159162 ━━━━━━━━━━━━━━━━━━━━ 102s 637us/step - accuracy: 1.0000 - loss: 1.0432e-04
Epoch 4/20
159162/159162 ━━━━━━━━━━━━━━━━━━━━ 101s 629us/step - accuracy: 1.0000 - loss: 1.0343e-04
Epoch 5/20
159162/159162 ━━━━━━━━━━━━━━━━━━━━ 100s 625us/step - accuracy: 1.0000 - loss: 9.4451e-05
Epoch 6/20
159162/159162 ━━━━━━━━━━━━━━━━━━━━ 104s 649us/step - accuracy: 1.0000 - loss: 1.0141e-04
Epoch 7/20
159162/159162 ━━━━━━━━━━━━━━━━━━━━ 103s 639us/step - accuracy: 1.0000 - loss: 9.2484e-05
Epoch 8/20
159162/159162 ━━━━━━━━━━━━━━━━━━━━ 106s 661us/step - accuracy: 1.0000 - loss: 8.8960e-05
Epoch 9/20
159162/159162 ━━━━━━━━━━━━━━━━━━━━ 111s 689us/step - accuracy: 1.0000 - loss: 8.7239e-05
Epoch 10/20
159162/159162 ━━━━━━━━━━━━━━━━━━━━ 102s 637us/step - accuracy: 1.0000 - loss: 8.0883e-05
Epo

In [48]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

159162/159162 ━━━━━━━━━━━━━━━━━━━━ 99s 624us/step


0.9999762427449564

In [51]:
print(y_pred)
print('\n\n',y_pred.shape)

[[ True False False]
 [ True False False]
 [False  True False]
 ...
 [False False  True]
 [ True False False]
 [False False  True]]


 (5093181, 3)


In [52]:
print(y_test)
print('\n\n',y_test.shape)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 ...
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


 (5093181, 3)
